[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/orkut"
  to = "/.netlify/functions/orkut"
  status = 200
  force = true

[[redirects]]
  from = "/api/orkut/*"
  to = "/.netlify/functions/orkut"
  status = 200
  force = true
